#!/usr/bin/env python3
"""Detect agent definition drift across the Claude, Codex, and Copilot platforms.

Scans the three mirrored agent directories (.claude/agents, .codex/agents,
.copilot/agents), extracts each agent's canonical name from its platform-specific
format, and reports any divergence in agent set across platforms.

Exit code:
  0 = no drift (all three platforms expose the same agent set)
  1 = drift detected (agent count or names diverge across platforms)
"""

import argparse
import json
import re
import sys
from pathlib import Path

PLATFORMS = {
    ".claude": {"dir": ".claude/agents", "ext": ".md"},
    ".codex": {"dir": ".codex/agents", "ext": ".toml"},
    ".copilot": {"dir": ".copilot/agents", "ext": ".md"},
}

NAME_RE_MD = re.compile(r"^name:\s*(.+?)\s*$")
NAME_RE_TOML = re.compile(r'^name\s*=\s*"([^"]+)"\s*$')


def extract_name_md(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as fh:
            for _ in range(20):
                line = fh.readline()
                if not line:
                    break
                match = NAME_RE_MD.match(line)
                if match:
                    return match.group(1).strip().strip('"').strip("'")
    except OSError:
        pass
    return file_path.stem


def extract_name_toml(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as fh:
            for line in fh:
                match = NAME_RE_TOML.match(line)
                if match:
                    return match.group(1).strip()
    except OSError:
        pass
    return file_path.stem


def scan_platform(root, platform):
    spec = PLATFORMS[platform]
    agents_dir = root / spec["dir"]
    names = set()
    if not agents_dir.is_dir():
        return names
    for fp in sorted(agents_dir.glob(f"*{spec['ext']}")):
        if spec["ext"] == ".toml":
            names.add(extract_name_toml(fp))
        else:
            names.add(extract_name_md(fp))
    return names


def build_report(root, source):
    platform_agents = {p: scan_platform(root, p) for p in PLATFORMS}
    counts = {p: len(a) for p, a in platform_agents.items()}
    if all(platform_agents.values()):
        common = set.intersection(*platform_agents.values())
    else:
        common = set()
    source_set = platform_agents[source]

    drift = {}
    for platform, agents in platform_agents.items():
        if platform == source:
            continue
        missing = source_set - agents
        extra = agents - source_set
        if missing or extra:
            drift[platform] = {"missing": sorted(missing), "extra": sorted(extra)}

    only_one = {}
    all_names = set().union(*platform_agents.values())
    for name in sorted(all_names):
        present_in = [p for p, a in platform_agents.items() if name in a]
        if len(present_in) == 1:
            only_one[name] = present_in[0]

    sets_equal = (
        platform_agents[".claude"]
        == platform_agents[".codex"]
        == platform_agents[".copilot"]
    )
    has_drift = not sets_equal

    return {
        "root": str(root),
        "source": source,
        "counts": counts,
        "common_count": len(common),
        "drift": drift,
        "only_one_platform": only_one,
        "has_drift": has_drift,
    }


def print_text(report):
    source = report["source"]
    print(f"Agent drift check (source={source})")
    print(f"root: {report['root']}")
    for platform in PLATFORMS:
        print(f"  {platform}: {report['counts'][platform]} agents")
    print(f"  common (all three): {report['common_count']}")

    only_one = report["only_one_platform"]
    if only_one:
        print("\n仅在单一平台存在的 agent:")
        for name, platform in only_one.items():
            print(f"  {name} -> {platform}")

    drift = report["drift"]
    if drift:
        print(f"\n相对基准源 {source} 的漂移:")
        for platform, diff in drift.items():
            if diff["missing"]:
                print(f"  {platform} 缺失: {', '.join(diff['missing'])}")
            if diff["extra"]:
                print(f"  {platform} 多出: {', '.join(diff['extra'])}")

    if report["has_drift"]:
        print("\n发现漂移: 三平台 agent 不一致")
    else:
        print("\n无漂移: 三平台 agent 一致")


def create_codex_wrapper(name, stem):
    """Generate a Codex TOML thin-wrapper for an agent whose canonical
    definition lives in .claude/agents/{stem}.md."""
    return (
        f'# Auto-generated by sync-agents.py --mirror\n'
        f'# Source: .claude/agents/{stem}.md\n'
        f'# 本 agent 是 {name} 的 Codex 平台薄封装。\n'
        f'# 完整定义见 .claude/agents/{stem}.md。\n'
        f'name = "{name}"\n'
        f'description = "{name} agent (Codex thin wrapper). '
        f'Full definition in .claude/agents/{stem}.md."\n'
        f'model = "gpt-5.5"\n'
        f'model_reasoning_effort = "high"\n'
        f'\n'
        f'developer_instructions = """\n'
        f'This is a thin wrapper for the {name} agent.\n'
        f'Please refer to the canonical definition in '
        f'.claude/agents/{stem}.md for full instructions.\n'
        f'All rules and constraints from the canonical definition apply.\n'
        f'"""\n'
    )


def create_copilot_wrapper(name, stem):
    """Generate a Copilot MD thin-wrapper for an agent whose canonical
    definition lives in .claude/agents/{stem}.md."""
    return (
        f'---\n'
        f'name: {name}\n'
        f'description: {name} agent (Copilot thin wrapper). '
        f'完整定义见 .claude/agents/{stem}.md。\n'
        f'platform: copilot\n'
        f'---\n'
        f'\n'
        f'# {name} Agent (Copilot - Thin Wrapper)\n'
        f'\n'
        f'本文件是 {name} 的 Copilot 平台薄封装，由 sync-agents.py --mirror 自动生成。\n'
        f'完整定义见 `.claude/agents/{stem}.md`。\n'
        f'所有规则和约束以 canonical 定义为准。\n'
    )


def mirror_agents(root, dry_run=False):
    """Mirror .claude agents to .codex and .copilot platforms.

    For every .claude/agents/*.md file, create a corresponding thin-wrapper
    in .codex/agents/*.toml and .copilot/agents/*.md when missing.  Existing
    target files are never overwritten.

    Returns a dict with per-platform copy counts and total skipped count.
    """
    claude_dir = root / ".claude" / "agents"
    codex_dir = root / ".codex" / "agents"
    copilot_dir = root / ".copilot" / "agents"

    if not claude_dir.is_dir():
        print("sync-agents: .claude/agents directory not found", file=sys.stderr)
        sys.exit(2)

    codex_dir.mkdir(parents=True, exist_ok=True)
    copilot_dir.mkdir(parents=True, exist_ok=True)

    mirrored_codex = 0
    mirrored_copilot = 0
    skipped = 0

    for src_file in sorted(claude_dir.glob("*.md")):
        stem = src_file.stem
        canonical_name = extract_name_md(src_file)

        codex_target = codex_dir / f"{stem}.toml"
        copilot_target = copilot_dir / f"{stem}.md"

        codex_exists = codex_target.exists()
        copilot_exists = copilot_target.exists()

        if codex_exists and copilot_exists:
            skipped += 1
            continue

        if dry_run:
            if not codex_exists:
                mirrored_codex += 1
            if not copilot_exists:
                mirrored_copilot += 1
            continue

        if not codex_exists:
            codex_target.write_text(
                create_codex_wrapper(canonical_name, stem), encoding="utf-8"
            )
            mirrored_codex += 1

        if not copilot_exists:
            copilot_target.write_text(
                create_copilot_wrapper(canonical_name, stem), encoding="utf-8"
            )
            mirrored_copilot += 1

    return {
        "mirrored_codex": mirrored_codex,
        "mirrored_copilot": mirrored_copilot,
        "skipped": skipped,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Detect agent drift across Claude, Codex, and Copilot platforms."
    )
    parser.add_argument(
        "--root", default=None, help="Repository root (auto-detected if omitted)"
    )
    parser.add_argument(
        "--source",
        default=".claude",
        choices=list(PLATFORMS.keys()),
        help="Baseline platform for missing/extra reporting (default: .claude)",
    )
    parser.add_argument(
        "--json",
        dest="as_json",
        action="store_true",
        help="Emit a JSON report instead of human-readable text",
    )
    parser.add_argument(
        "--mirror",
        action="store_true",
        help="Mirror .claude agents to .codex and .copilot (thin wrappers for missing files only)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="With --mirror: show what would be copied without creating files",
    )
    args = parser.parse_args()

    if args.root:
        root = Path(args.root).resolve()
    else:
        root = Path(__file__).resolve().parent.parent

    if not root.is_dir():
        print(f"sync-agents: root directory not found: {root}", file=sys.stderr)
        sys.exit(2)

    if args.mirror and args.as_json:
        print("sync-agents: --mirror and --json are mutually exclusive", file=sys.stderr)
        sys.exit(2)

    if args.dry_run and not args.mirror:
        print("sync-agents: --dry-run requires --mirror", file=sys.stderr)
        sys.exit(2)

    if args.mirror:
        result = mirror_agents(root, dry_run=args.dry_run)
        label = "(dry-run) " if args.dry_run else ""
        print(
            f"mirror: {label}"
            f"{result['mirrored_codex']} agents copied to .codex, "
            f"{result['mirrored_copilot']} agents copied to .copilot, "
            f"{result['skipped']} skipped (already exist)"
        )
        sys.exit(0)

    report = build_report(root, args.source)

    if args.as_json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
    else:
        print_text(report)

    sys.exit(1 if report["has_drift"] else 0)


if __name__ == "__main__":
    main()
