name: Runner Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64, sre/foundation-l0]
    steps:
      - run: echo "runner works" && hostname && whoami && date
